# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa8be8a92d2a4c503e0bdb024b42753802a7d9dd9b68f13c5aebde2c99ae969b453098db2c12d5d5e4ec72189bf46797b19ad67b7e0ec2ed0e7076da2a36bba

test:
  secret_key_base: 1e08c607448d0897a70ed03f95c7185259aa4d044b5529f819e2ac455c9788efe1787c4c2ff531ccd664ed7e4c5d8105951b5539b6fcd3d3573c74c1d9d72f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
